name: Update Views Banner

on:
  schedule:
    - cron: "0 */6 * * *"   # 6 saatte bir çalışır
  workflow_dispatch:         # elle çalıştırma için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pillow requests
      - name: Generate banner
        env:
          GITHUB_USERNAME: nikitagofi
        run: python tools/generate_views.py
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/views.png
          git commit -m "chore: update rainbow views banner" || echo "no changes"
          git push
